---
- name: debian | installing pre-reqs
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip

- name: debian | downloading filebeat
  get_url:
    url: "{{ es_filebeat_debian_dl }}"
    dest: "/opt/{{ es_filebeat_debian_package }}"

- name: debian | installing filebeat
  apt:
    deb: "/opt/{{ es_filebeat_debian_package }}"
    state: present
